// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jpkxgzisejzblnbpttik.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Impwa3hnemlzZWp6YmxuYnB0dGlrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzU0ODYxOTIsImV4cCI6MjA5MTA2MjE5Mn0.HSWRQyDadsgCIrYVF3zJZg53GvlBKdmE8myhq0DCQio";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});